### ISSUE TITLE
Blueprint: Can't Scroll on Overflow

### ISSUE THREAD

**Issue by merlinstardust** [MeteorToys/allthings#36]
Love the new Blueprint orb. Unfortunately, when I hover over a template with data that overflows the orb, I can't scroll the orb to see the rest of the data. Once I go to the orb scroll bar, I am no longer hovering over the template and so no data appears.

**Comment by msavin** [comment]
Good catch - update coming in Blueprint v2 :)

**Comment by merlinstardust** [comment]
Awesome. Thanks!

**Comment by msavin** [comment]
In the meanwhile, maybe this trick can help:

``` css
#MeteorToys_template {
    height: 900px  !important
    width: 600px !important
}
```
